name: 'Build Isabelle Theory'
description: 'Build an Isabelle theory file.'

inputs:
  theory-root:
    description: 'Path to the root of the theory.'
    default: ''
  session-name:
    description: 'Session name to build.'
    default: ''
  depends:
    description: 'Whitespace-separated list of dependencies (url@ref).'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print working directory (debug)
      run: |
        echo "PWD: $(pwd)"
        echo "Listing contents:"
        ls -la
      shell: bash

    - name: Ensure build script is executable
      run: chmod +x ./build_isabelle_theory
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Run build script
      run: ./build_isabelle_theory "${{ inputs.theory-root }}" "${{ inputs.session-name }}" "${{ inputs.depends }}"
      shell: bash
      working-directory: ${{ github.workspace }}
