name: 'Build Isabelle Theory'
description: 'Build an Isabelle theory file'
inputs:
  isabelle-version:
    description: 'Version of Isabelle to build with, currently only `2021-1` is supported'
    required: true
  theory-root:
    description: 'Path to the root of the theory. This defaults to the root of the repository.'
    default: ''
  session-name:
    description: 'The session name to build (with isabelle build -b session-name). This defaults to the name of the repository.'
    default: ''
  depends:
    description: 'A whitespace-separated list of other repositories containing sessions that are required to build the session in the current repository. Use url@ref syntax to specify a git ref.'
    default: ''
#outputs: # TODO
#  heap-image:
#    description: "path to the built image"
#    value:
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: build_isabelle_theory "${{ inputs.isabelle-version }}" "${{ inputs.theory-root }}" "${{ inputs.session-name }}" "${{ inputs.depends }}"
      shell: bash

