name: 'Build Isabelle Theory'
description: 'Build an Isabelle theory file'
inputs:
  isabelle-version:
    description: 'Version of Isabelle to build with, currently only `2021-1` is supported'
    required: true
#outputs: # TODO
#  heap-image:
#    description: "path to the built image"
#    value:
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: build_isabelle_theory

