name: 'Build Isabelle Theory'
description: 'Build an Isabelle theory file'
inputs:
  isabelle-version:
    description: 'Version of Isabelle to build with, currently only `2021-1` is supported'
    required: true
  custom-isabelle-url:
    description: 'If you want to use a non-standard version of isabelle to build your package, use this option to specify an archive file url. You still need to specify isabelle-version, however.'
    default: ''
  theory-root:
    description: 'Path to the root of the theory. This defaults to the root of the repository.'
    default: ''
  session-name:
    description: 'The session name to build (with isabelle build -b session-name). This defaults to the name of the repository. You can also list multiple sessions, separated by whitespace.'
    default: ''
  depends:
    description: 'A whitespace-separated list of other repositories containing sessions that are required to build the session in the current repository. Use url@ref syntax to specify a git ref.'
    default: ''
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install xonsh python3-yaml atool texlive texlive-plain-generic texlive-science texlive-latex-extra
      shell: bash
    - run: build_isabelle_theory "${{ inputs.isabelle-version }}" "${{ inputs.theory-root }}" "${{ inputs.session-name }}" "${{ inputs.depends }}" "${{ inputs.custom-isabelle-url }}" "${{ inputs.report_url }}" "${{ inputs.report_secret }}"
      shell: bash

