#!/usr/bin/env bash

set -e

projname=$(basename $(pwd))
isa_ver="$1"
rootdir="$2"
session="$3"

if [ "x$session" == "x" ]; then
    session=projname
fi

echo "Fetching Isabelle:"

case $isa_ver in
    2021-1)
        wget -nv -O - https://isabelle.in.tum.de/dist/Isabelle2021-1_linux.tar.gz | tar -xzf - 
        cd Isabelle2021-1
        isa_base=$(pwd)
        ;;
    *)
        echo "Unknown Isabelle version `$isa_ver`."
        exit 1
        ;;
esac


echo "Adding project sources:"
root="$projname/$rootdir"
ln -s $GITHUB_WORKSPACE "$isa_base/src/$root"
cd "$isa_base"
echo "Adding root: src/$root"
echo "src/$root" >> ROOTS
echo "building with: ./bin/isabelle build -b \"$session\""
./bin/isabelle build -b "$session"
